namespace Assets.HeroEditor4D.InventorySystem.Scripts.Enums
{
    public enum ItemClass
    {
        Undefined,
        Dagger,
        Sword,
        Axe,
        Blunt,
        Lance,
        Wand,
        Bow,
        Light,
        Heavy,
        Ring,
        Necklace,
        Food,
        Potion,
        Scroll,
        Bomb,
        Pickaxe,
        Claw,
        Fang,
        Skin,
        Firearm,
        Talisman,
        Wood,
        Ore,
        Alloy,
        Wings,
        Shell,
        Bone,
        Leather,
        Tail,
        Gunpowder
    }
}